### ISSUE TITLE
Two active options in the main menu

### ISSUE THREAD

**Issue by jperezmota** [jperezmota/perspective-web-app#10]
When the user clicks on the third or fourth option of the main menu, the previous menu option keeps active, instead of just leaving active the last option clicked.

**Bug example**

![image](https://user-images.githubusercontent.com/36488188/46037813-53b9fe80-c0d7-11e8-9932-9b1b737812fb.png)

**Comment by JthanDev** [comment]
Fixed with this issue: https://github.com/jperezmota/perspective-web-app/issues/15
